### ISSUE TITLE
Dockerize app /set up Github Actions

### ISSUE THREAD

**Issue by BurningSquid** [teacherc/spheri-app#3]
While this is applicable to deployment in a broad sense, it is critical to interacting with other developers (either on the internet or on local teams). There is not a single "right" way to set up a python project, but any of the commonly suggested ways focus around module architecture. Might look something like this: 

```
Project
-/module
--__init__.py
--__main__.py
--...other files
--/tests
--__init__.py
--...test_main.py
--....etc
```

if you have multiple modules I typically do something like this: 

```
Project
-src
--/module 1
---__init__.py
---__main__.py
--...other files
--/module 2
---....
--/tests
---/module 1
----__init__.py
----...test_main.py
---/module 2
----....
```

This has some benefits, for example: 

- if you need a module to be published as a library (i.e. via [poetry](https://python-poetry.org/) or published via an artifact feed it must be in this form
- separates python code from configuration code. Generally just easier to organize things if code and configuration are separate
- Allows you to run the module using `python -m module` which uses __main__.py as the entrypoint. convenient for docker run entrypoints if you need
- test organization and discovery is easier

probably missing some of the factors here but I think you get the point. I would check out [PEP](https://peps.python.org/pep-0008/) for "official" thoughts here. 

Now let's talk about your codebase specifically. 

- I would start by making a module folder rather than having the whole project be the module
-  you already have an \_\_init\_\_ but main should be called \_\_main\_\_.py
- Generally I would start breaking out your main script a bit into logical boundaries. For example the dataclasses (and validators etc per #1) might go in their own file, I typically put pull out api routes into their own submodule if there are enough of them. Don't need to go crazy here just a bit of organization. 
- When you do break it out make sure to use relative imports, for example say you have two files: 

helpers.py
```
def function():
...
```

then in __main__.py

```
from .helpers import function
```

- secrets and environmental variables should be kept in a .env file (using [pydotenv](https://peps.python.org/pep-0008/)). This prevents the need for a user to have to create the config.py file themselves all they have to do is create the .env file. Then in a settings.py file you can use os.environ["secret"] and find_dotenv() to get access to the environmental variables. This ties into #2 as well in that authentication secrets and stuff can change in deployment.

**Comment by teacherc** [comment]
@BurningSquid The good news, is that I change the file structure. The bad news is that I cannot figure out how to deploy a working version to my Google App Engine site (I've reverted to the old version).

**Comment by BurningSquid** [comment]
Ah, glad you brought this up. So you have found the intersection between development conventions and deployment requirements! So in this case google app engine expects files to be named or organized in a specific way (typically located in the root directory and called "app.py" or something you specify). So you are left with a dilemma: 

1) You want to follow proper package structure as python prefers
2) You want your deployed app to follow Google App Engine structure like GCP prefers

The, or at least the answer I typically go to, lies in your Docker setup. You should have a docker file,m or [multi-stage build](https://docs.docker.com/build/building/multi-stage/) with a "production" stage, that creates an image with the code structured in the Google App Engine preferred way

**Comment by BurningSquid** [comment]
To make it a bit more clear you might have something like this (btw this is off the cuff so don't take this verbatim) 

```
FROM python:3.8.12 AS base
 
# install python env deps here

FROM base AS development
# install python dev deps here like pytest etc

# add code to root image in it's native structure
ADD . .

FROM base AS production
# make the app path env variable equal to whatever google app engine requires it to be
ENV APP_PATH=/app

# change working directory to the app path and add code to it
WORKDIR $APP_PATH
ADD spheri/ $APP_PATH
```

**Comment by teacherc** [comment]
@BurningSquid So - this is a Dockerfile?

**Comment by teacherc** [comment]
I'm watching these videos to help me get started:
https://www.youtube.com/watch?v=uI1mzwtx4ZM

https://www.youtube.com/watch?v=zpkqNPwEzac

**Comment by teacherc** [comment]
and this one on secrets - https://www.youtube.com/watch?v=JIE89dneaGo

**Comment by teacherc** [comment]
Next steps:

- [ ] 1. Create a Dockerfile that works locally (and a docker compose yml with env file)
- [ ] 2. Add the container image to the Github container registry
- [ ] 3. Connect Github Actions to GCP
- [ ] 4. Handle secrets in GCP
- [ ] 5. Preview in GCP staging
- [ ] 6. Deploy to production (replace current Google App Run instance)

**Comment by teacherc** [comment]
Ah, it looks like I need to do something like this: https://codelabs.developers.google.com/codelabs/secret-manager-python#0

**Comment by teacherc** [comment]
@BurningSquid Actually, based on your knowledge of GCP, should I have to use the Python Secrets API, or should Google Cloud Run be able to parse my use of getenv to match those to secrets I've stored?

**Comment by teacherc** [comment]
@BurningSquid Figured it out!

**Comment by BurningSquid** [comment]
So sorry had a bunch of life stuff come up this week. Sounds like you have been making progress!

**Comment by teacherc** [comment]
@BurningSquid No worries :-)
